import React from 'react'
import './About.css'
function About() {
    return (
        <div className='charts-container'>
            <h5>Top 400 polskich streamerów</h5>
            <div className='streamers-list chart'>
                <span>xayoo_</span>
                <span>EWROON</span>
                <span>YoungMulti</span>
                <span>vysotzky</span>
                <span>Popo</span>
                <span>LukiSteve</span>
                <span>xmerghani</span>
                <span>mlodziutki7</span>
                <span>Franio</span>
                <span>xth0rek</span>
                <span>IzakOOO</span>
                <span>H2P_Gucio</span>
                <span>Grendy</span>
                <span>Aki_997</span>
                <span>parisplatynov</span>
                <span>MokrySuchar</span>
                <span>PLKDAMIAN</span>
                <span>polsatgames</span>
                <span>BanduraCartel</span>
                <span>MrDzinold</span>
                <span>PAGO3</span>
                <span>Jacob4TV</span>
                <span>sawardega</span>
                <span>Diables</span>
                <span>wujabudyn</span>
                <span>Mandzio</span>
                <span>pisicela</span>
                <span>RybsonLoL_</span>
                <span>GG33__</span>
                <span>Kubx</span>
                <span>Kasix</span>
                <span>qlnek</span>
                <span>isamu</span>
                <span>puniogaming</span>
                <span>adamcy_</span>
                <span>Overpow</span>
                <span>Takuu_</span>
                <span>olszakumpel</span>
                <span>pashaBiceps</span>
                <span>Slayproxx</span>
                <span>Kubon_</span>
                <span>MORK</span>
                <span>Snax</span>
                <span>tamae_senpai</span>
                <span>GALINEOS</span>
                <span>ElekKartofelek</span>
                <span>ZONY</span>
                <span>KamiFN1</span>
                <span>xspeedyq</span>
                <span>xntentacion</span>
                <span>remsua</span>
                <span>Testree</span>
                <span>JacexDowozWideo</span>
                <span>Gluhammer</span>
                <span>Jenkinsss</span>
                <span>delordione</span>
                <span>BlackFIreIce</span>
                <span>peVoR13</span>
                <span>ArQuel</span>
                <span>exhiie</span>
                <span>Pelcu</span>
                <span>prawda_futbolu</span>
                <span>VgZ2k</span>
                <span>RockAlone</span>
                <span>Cinkrofwest</span>
                <span>Patiro</span>
                <span>Bonkol</span>
                <span>Kaseko</span>
                <span>Nieuczesana</span>
                <span>demonzz1</span>
                <span>GramyPomagamy</span>
                <span>Kalach444</span>
                <span>MaaiLinh</span>
                <span>IceFireFN</span>
                <span>Nervarien</span>
                <span>inet_saju</span>
                <span>Angela35</span>
                <span>cygan___</span>
                <span>gangamurun</span>
                <span>meduska</span>
                <span>Alviniasty</span>
                <span>Miszel</span>
                <span>BaniakBaniaka</span>
                <span>tiger_scot</span>
                <span>seny</span>
                <span>Matek</span>
                <span>Diabeuu6</span>
                <span>MrCreatifee</span>
                <span>RandomBruceTV</span>
                <span>AwizoTV</span>
                <span>czesio_invi</span>
                <span>NewMultiShow</span>
                <span>ozzi_rider</span>
                <span>byalli</span>
                <span>Lachu</span>
                <span>masle1</span>
                <span>NietoperzByku</span>
                <span>Nexos</span>
                <span>EnigmaStreamuje</span>
                <span>AikoiEmil</span>
                <span>edenitoo</span>
                <span>Olaczka</span>
                <span>IndyStarCraft</span>
                <span>AnonymoBeOne</span>
                <span>Vdr1984</span>
                <span>shini_waifu</span>
                <span>zeekxD</span>
                <span>CrownyCro</span>
                <span>Fatek_</span>
                <span>Smaczny</span>
                <span>xN0rth</span>
                <span>iammielzky</span>
                <span>hades1337</span>
                <span>tudsoNN</span>
                <span>xghoost__</span>
                <span>SpiralusGTM</span>
                <span>Miniuwa</span>
                <span>Lewus</span>
                <span>trapkipa</span>
                <span>innocenttt</span>
                <span>ChudyChudziutki</span>
                <span>KamilEater</span>
                <span>BagietkaYT</span>
                <span>Spartiatix</span>
                <span>Navcia</span>
                <span>Troglodytaa</span>
                <span>artorr</span>
                <span>Plaga</span>
                <span>xToM223</span>
                <span>Kamyk</span>
                <span>Kaiser338</span>
                <span>neoG5</span>
                <span>Kezman22</span>
                <span>Jas1ek</span>
                <span>PaPaPawian</span>
                <span>srokaaa_</span>
                <span>xEmtek</span>
                <span>DMGPOLAND</span>
                <span>Patryk_Krutyj</span>
                <span>Michu_HM</span>
                <span>size2137</span>
                <span>Borys8</span>
                <span>Avalkiz</span>
                <span>LysssyProo</span>
                <span>achtenWlodar</span>
                <span>Anterias</span>
                <span>blachu_</span>
                <span>Sinmivak</span>
                <span>Bobeek</span>
                <span>Mamm0n</span>
                <span>Lutel</span>
                <span>Skaaza_</span>
                <span>kiiissa</span>
                <span>VooltBanicja</span>
                <span>LosiuGra</span>
                <span>Sidneuke</span>
                <span>3vildelta</span>
                <span>shreddin_</span>
                <span>youlia</span>
                <span>dychacs</span>
                <span>KenoN__</span>
                <span>bejott</span>
                <span>mrs_honey</span>
                <span>packo</span>
                <span>BixenteHS</span>
                <span>Lipej</span>
                <span>k4rolinv_</span>
                <span>MrSetoKami</span>
                <span>Druvik_</span>
                <span>UrQueeen</span>
                <span>arhneu</span>
                <span>emelejt</span>
                <span>Ortis</span>
                <span>Haemhype</span>
                <span>NadinWins</span>
                <span>SirMisiek</span>
                <span>DawidCzerw</span>
                <span>Qreii</span>
                <span>Niklaus</span>
                <span>AL3XANDRAS</span>
                <span>suziannna</span>
                <span>gieras51</span>
                <span>Monsteryoo</span>
                <span>kycu</span>
                <span>mlooda_</span>
                <span>Tomek_Poradzisz</span>
                <span>Mamiko</span>
                <span>chess24pl</span>
                <span>advisefn</span>
                <span>LakarnumPL</span>
                <span>TuttekHS</span>
                <span>xkaleson</span>
                <span>Bladii309</span>
                <span>jasiuspokojnie</span>
                <span>kubikcs</span>
                <span>call_me_piotr</span>
                <span>PulchnyNiedzwiedz</span>
                <span>szysszka_</span>
                <span>JohnVerrinePL</span>
                <span>jaskol95</span>
                <span>tyrisftw</span>
                <span>Derp_Shaco</span>
                <span>Kasia_22</span>
                <span>melod_ja</span>
                <span>L2pLelouch</span>
                <span>kinzzami</span>
                <span>Rusekk_</span>
                <span>zuberx</span>
                <span>senekofobia</span>
                <span>angelkacs</span>
                <span>bruz777</span>
                <span>Stazjaa</span>
                <span>japko4</span>
                <span>darkocsgo</span>
                <span>Menders_7</span>
                <span>Makito_</span>
                <span>Shiianah</span>
                <span>VanessaSzwaczka</span>
                <span>ThrashingMadPL</span>
                <span>Plummek</span>
                <span>eldamiano07</span>
                <span>NEEXcsgo</span>
                <span>defles3</span>
                <span>MICHUcs_go</span>
                <span>SobeQ_</span>
                <span>9kier</span>
                <span>kesZu_h3</span>
                <span>AdziOo</span>
                <span>Koniekoo</span>
                <span>bjushee</span>
                <span>SZPERO</span>
                <span>TheFakeOneGG</span>
                <span>PajotreQ</span>
                <span>Dawidu91</span>
                <span>finesGG</span>
                <span>simplywojtek</span>
                <span>marcysia_uwu</span>
                <span>Putrefy</span>
                <span>Chrisztof</span>
                <span>grad_u</span>
                <span>Sevel07</span>
                <span>veggie16</span>
                <span>Slowek</span>
                <span>Kazama5</span>
                <span>Flothar</span>
                <span>PIKACZUUU</span>
                <span>LetsGoTryYT</span>
                <span>strojny</span>
                <span>Madien</span>
                <span>Zbrojson</span>
                <span>xype1337</span>
                <span>mwlky</span>
                <span>dmajszi</span>
                <span>WizzuWizualnie</span>
                <span>DED87</span>
                <span>valorantleague_east</span>
                <span>DayRa1sE</span>
                <span>adrian1g__</span>
                <span>Mitsun_</span>
                <span>veu_gg</span>
                <span>Ungentium</span>
                <span>Liazal</span>
                <span>1wron3k</span>
                <span>jcchochlik</span>
                <span>Sanchez</span>
                <span>daysi1025</span>
                <span>Harnaas_</span>
                <span>Cathlynes</span>
                <span>xNzq</span>
                <span>KECAJEK</span>
                <span>Czukasz</span>
                <span>RajotGPLAY</span>
                <span>NVIDIAGeForcePL</span>
                <span>Esports_Assoc</span>
                <span>ChilledYakuza</span>
                <span>FURAZEK</span>
                <span>Czajnikkk__</span>
                <span>PeciuCJDR</span>
                <span>Namaenonaii</span>
                <span>ZahaCzai</span>
                <span>Inspirawka</span>
                <span>pkr29</span>
                <span>daarja</span>
                <span>mlodyo</span>
                <span>kingakujawska</span>
                <span>Rafis0</span>
                <span>MARO3</span>
                <span>brysiunya</span>
                <span>TVKowalowe</span>
                <span>swali__</span>
                <span>DGminise</span>
                <span>SzklanaY2J_</span>
                <span>GraBaRtek</span>
                <span>Pidzam</span>
                <span>sandrulaax</span>
                <span>majkibets</span>
                <span>damiefifa</span>
                <span>SouShibo</span>
                <span>TeKoTube</span>
                <span>malyszewski</span>
                <span>Kangurek_Kao_Pej</span>
                <span>Hiratoshi_</span>
                <span>Silv4n</span>
                <span>GMPakleza</span>
                <span>dYnkSxMonster</span>
                <span>Szopa666h3</span>
                <span>HIGHSTYLED</span>
                <span>Orchidia92</span>
                <span>P2Wteam</span>
                <span>STOMPcsgo</span>
                <span>mrs_NOCKA</span>
                <span>xWeza</span>
                <span>hvndl</span>
                <span>yaotziN_</span>
                <span>pukistylee</span>
                <span>PKziomal</span>
                <span>DawidSSonek</span>
                <span>ZavadaHS</span>
                <span>TheChucken</span>
                <span>PiotrSugar_</span>
                <span>FunDlaLam</span>
                <span>rybeq88</span>
                <span>Maja__x</span>
                <span>Kagaminium</span>
                <span>MKRR3</span>
                <span>bimbesh</span>
                <span>devilpiotr</span>
                <span>Tysiologia</span>
                <span>MiksonFN</span>
                <span>melfonide</span>
                <span>thequdee</span>
                <span>Rysiek</span>
                <span>KapitanAlien</span>
                <span>tox1c_adrian</span>
                <span>luki3</span>
                <span>Mloteczka</span>
                <span>Kozihq</span>
                <span>BuraczekNadaje</span>
                <span>Maggothy</span>
                <span>Bungo21</span>
                <span>Godiood</span>
                <span>ChappyCherri</span>
                <span>AgraveiN</span>
                <span>Miszkinek</span>
                <span>vvarion</span>
                <span>doktorhodo</span>
                <span>Maciej_Jermakow</span>
                <span>AGO_matiboro</span>
                <span>og1ii</span>
                <span>Esgaroth16</span>
                <span>LegioN</span>
                <span>dasiek01</span>
                <span>profesorek_</span>
                <span>Nitekk_</span>
                <span>Wojtusialke</span>
                <span>lempiank</span>
                <span>olcziiix</span>
                <span>Brunecia</span>
                <span>Cashnalot</span>
                <span>khamires</span>
                <span>Denzaay</span>
                <span>GugaGamerka</span>
                <span>liderus_</span>
                <span>gremIInek</span>
                <span>Besi523</span>
                <span>RedBullPL</span>
                <span>kotkocislaww</span>
                <span>LiLqki</span>
                <span>zgrywu_</span>
                <span>Smarte13</span>
                <span>szamanfn</span>
                <span>Tomiader</span>
                <span>Carrioner</span>
                <span>klqudka</span>
                <span>PanPawlowski</span>
                <span>Kubson92</span>
                <span>VampLola</span>
                <span>RagingEngaging</span>
                <span>Frytka</span>
                <span>Emil</span>
                <span>kebcioo</span>
                <span>chocolate_puma</span>
                <span>hajmer_</span>
                <span>RejSen</span>
                <span>arax_x</span>
                <span>Kozok</span>
                <span>Kat_Alien</span>
                <span>Bunny_Marthy</span>
                <span>LAUCILKA</span>
                <span>ciriell</span>
                <span>kromkachleba</span>
                <span>ukulula</span>
            </div>
        </div>
    )
}

export default About